disabled_rules:
  - function_parameter_count
  - function_body_length
  - type_body_length
  - force_try
  - force_cast
  - cyclomatic_complexity
  - identifier_name
  - type_name
  - file_length
  - large_tuple
  - nesting
  - unused_setter_value
  - todo
  - attributes
line_length: 180
included:
  - GistHub
  - Packages
excluded:
  - Packages/Sources/GistHubGraphQL
  - Packages/**/Tests
  - Packages/**/.build
  - Packages/Server
