disabled_rules:
  - function_parameter_count
  - function_body_length
  - type_body_length
  - force_try
  - force_cast
  - cyclomatic_complexity
  - identifier_name
  - type_name
  - line_length
  - file_length
  - large_tuple
  - nesting
  - unused_setter_value
  - todo
opt_in_rules:
- attributes
attributes:
  always_on_line_above: ["@objc", "@nonobjc"]
line_length: 160
nesting:
  type_level: 2
function_body_length:
  warning: 80
cyclomatic_complexity:
  warning: 15
included:
  - GistHub
  - Packages
excluded:
  - Packages/**/Tests
