// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// Autogenerated input type of AddStar
public struct AddStarInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    starrableId: ID,
    clientMutationId: GraphQLNullable<String> = nil
  ) {
    __data = InputDict([
      "starrableId": starrableId,
      "clientMutationId": clientMutationId
    ])
  }

  /// The Starrable ID to star.
  public var starrableId: ID {
    get { __data["starrableId"] }
    set { __data["starrableId"] = newValue }
  }

  /// A unique identifier for the client performing the mutation.
  public var clientMutationId: GraphQLNullable<String> {
    get { __data["clientMutationId"] }
    set { __data["clientMutationId"] = newValue }
  }
}
