// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of AddStar
  static let AddStarPayload = Object(
    typename: "AddStarPayload",
    implementedInterfaces: []
  )
}