name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Server
        run: cd Packages/Server; swift test
