name: Git Tag

on:
  push:
    branches:
      - CI/Release

jobs:
  tag:
    name: Swift-macOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Git tag and push
        run: sh ci_scripts/tag_when_release.sh
